### ISSUE TITLE
No Darkmode

### ISSUE THREAD

**Issue by DevX-Cipher** [ChGen/DarkEnforcer#1]
hi i just tried your example and it does not work also the screen shot you have how did you make it dark mode

**Comment by ChGen** [comment]
@modz2014 , follow this steps:
1) Prepare MS VS2022, Windows 11 22H2 amd64.
2) Open `.sln` file with Visual Studio, build in Debug mode.
3) Switch to Windows 11 Dark  theme. Note, that standard `cleanmgr.exe` isn't dark.
4) Before running DarkEnforcer, save important files, since it will inject `dll` to all processes and something may crash.
5) Run DarkEnforcer via Visual Studio (without extra elevation/admin rights). It won't show any window, probably. You will see new  running process in Task Manager.
6) Run standard `cleanmgr.exe` without extra elevation/admin rights. You should see that it's mostly black now.
7) When you finished, kill DarkEnforcer process.

**Comment by DevX-Cipher** [comment]
can we make this a dynamic library so it application can use it or also i ran your app and click on my button nothing happens

**Comment by ChGen** [comment]
@modz2014 , that button probably does nothing. `dll` is injected on DarkEnforcer start. 
All 'dark' logic is in the dll and could be reused. So its already in dynamic library.

**Comment by DevX-Cipher** [comment]
well nothing happens

**Comment by ChGen** [comment]
@modz2014 , so you switched to dark mode, DarkEnforcer process is running and when you run `cleanmgr` (without Admin) it is not black?

**Comment by DevX-Cipher** [comment]
yes i have fixed something also the black is way to dark

**Comment by ChGen** [comment]
@modz2014 , I've found some uncommitted lines, so I pushed them. Try to kill process, pull changes and rebuild solution. Then follow instructions above - it still works for me.

**Comment by ChGen** [comment]
About theming yes, some frames are still missing, and some shades may be not the perfect match.

**Comment by DevX-Cipher** [comment]
ok cool
